name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trigger Vercel Deployment
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl "${VERCEL_DEPLOY_HOOK}"